### ISSUE TITLE
SQL-injection vulnerability

### ISSUE THREAD

**Issue by fgeek** [phpcollab/phpcollab#22]
Advisory here: http://www.vulnerability-lab.com/get_content.php?id=1898

Vulnerability Laboratory said that they were unable to contact you. Is this vulnerability valid and do you plan to fix it in some release? I can also reproduce it if needed.

**Comment by mindblender** [comment]
Hi @fgeek 

Yes, v2.5x has several SQL vulnerabilities in it.  The issue is we are at a crossroad since the original phpCollab code is so old.  Do we try and do patches and fix all the issues, and not just SQL vulnerabilities but a lot of others, or do we rewrite it from the ground up.  Having worked on the code for a long time, I am starting to lean towards rewriting it from scratch so that we can easily embrace modern dev techniques as well as make the application more flexible.

As always, I'm open to suggestions/feedback.

Jeff

**Comment by project29k** [comment]
I started phpcollab in February 2002, and of course everything is old: php, css, js, html
For example, with php7, the mysql driver is deprecated, you have to use mysql improved or pdo
The design is old, not responsive
Now I play with material design lite: https://readerself.com/demo/?email=example@example.com&password=example

Regularly I want to start again, because I think that today we can do something very strong.

But I don't know if there are still people interested in self hosted for project management
There are so many online services

Are the former users ready to upgrade using the command line (composer install, bower install ...)

If we change, we have to move to a strong framework
Now I work with Symfony, we can prepare nice bundles with existing features

The major question is about database: do we make a cleanup (foreign keys, replace mediumint by int, real date/datetime fields ...) or start a new structure (but we have to prepare a migration for existing users)

project29k (ceam)

**Comment by mindblender** [comment]
Closing this since several SQL vulnerabilities have been fixed in the master branch and will be included in the next release.
