### ISSUE TITLE
Feat: Send notification when a file approval status is changed

### ISSUE THREAD

**Issue by mindblender** [phpcollab/phpcollab#42]
When a user changes the approval status of a file, a notification should go out alerting the team that the file approval status has been updated.

Task: Add file approval status change notification

**Comment by mindblender** [comment]
Also should send a notification when an approval comment is added

**Comment by mindblender** [comment]
Added a new notification when a linked content file approval statue changes, via the approval tracking form, an email notification will be sent out to team members.

**Comment by Vnonni** [comment]
Dear Jeff
we would like to test the new version 2.7.2 that you released, also because for what we have read this should provide some functionality we implemented on our own on past versions

only, by reading the message on the main page you say that you're working to let this new version working on PHP 7.3.x
what does it mean: does the version 2.7.2 work on a later version of PHP such as 7.4.1 (the one we have already installed)?

thanks for your answer

**Comment by mindblender** [comment]
Hi,

phpCollab 2.7.2 has been tested against PHP 7.2.1.  I am in the process of
testing with 7.3.x.

I have not kept up with the latest PHP version releases, so was not aware
7.4.x had come out as well so I will take a look at what differences there
are and see if there are any breaking changes and will also begin testing
against 7.4.x.

Regards,
Jeff
