### ISSUE TITLE
upgrade phpcollab

### ISSUE THREAD

**Issue by algores** [phpcollab/phpcollab#43]
Dear mindblender,
first of all thank you for your work, we are using phpcollab 2.5.1 what is the right upgrade process from phpcollab 2.5.1 to phpcollab 2.6 or 2.7 ?

Best regards,
Daniele

**Comment by mindblender** [comment]
@algores Since there are no Database changes in the latest releases, you should be able to just replace the files and be back up and running on the latest version.  As always, I would recommend that you backup your phpCollab files and database prior to any update, just to be safe.  Also, always make sure you keep your `includes/settings.php` file, and the `files/`, `logos_clients` folders.
