### ISSUE TITLE
e-mail notifications page

### ISSUE THREAD

**Issue by algores** [phpcollab/phpcollab#47]
Dear mindblender,
e-mail notifications page /preferences/updatenotifications.php don't save settings and I think there is something of strange to page title or in the notification logic because notification is sent only if  notification value is "0" (ex: $listNotifications["taskAssignment"] == "0")

Centos 6.10 (Plesk Obsidian 18.0.21)
phpCollab 2.7.0 (fresh installation with data imported)
Apache 2.2.15 (nginx as reverse proxy)
PHP version 7.3.13 fastcgi

Thank you

**Comment by mindblender** [comment]
Thank you for letting me know about this.  I'll take a look and get it fixed.

**Comment by mindblender** [comment]
@algores I was not able to reproduce any issue with saving a notification preference.

That being said, yes the code logic appears to be backwards and needs to be fixed, but that will require making data changes with an upgrade script and is low on the priority list.  Right now, 0 means true, 1 means false.  It should be the opposite. 😬

It is on the agenda for v3 to fix these little nuances.

Please re-open this issue if you are still unable to save your notification settings. You might also try PHP 7.2.x since we have not done exhaustive testing on 7.3.x yet.
